import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Preloader from './../Preloader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rokosz Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-b`}
      >
       <div className="bg-black text-white flex overflow-x-auto space-x-4"> 

       
        <Preloader/>
        {children}
        </div>
      </body>
    </html>
  );
}
